name: GitHub Actions Demo
run-name: Testing out GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "This is very easy, and easy-to-understand"
